// Danish copy for the page, dialogs, downloaded brief and portfolio projects.
window.danishTranslations = {
  skip: 'Spring til indholdet',
  navAbout: 'Vores vision',
  navServices: 'Sådan arbejder vi',
  navWork: 'Udvalgte projekter',
  navContact: 'Lad os tale sammen',
  heroTitle: 'Dansk inspiration.<br>Muligheder i Kina.',
  heroDescription: 'Bevar det, der gør dit brand dansk. Tilpas fortællingen og den digitale oplevelse til et kinesisk publikum med markedsindsigt og kreativ formidling.',
  heroExplore: 'Udforsk mulighederne',
  heroWork: 'Se vores projekter',
  heroBottom: 'To perspektiver. Én fælles ambition.',
  aboutEyebrow: 'VI FORBINDER KULTURER OG MULIGHEDER',
  aboutTitle: 'Det bedste fra Danmark.<br>En verden af muligheder.',
  aboutLead: 'En platform, der forbinder danske brands med Kina og gør deres særlige produkter og fortællinger lettere at forstå.',
  aboutText: 'Best of Denmark bidrager med indsigt i det kinesiske marked og kultur, netværk og muligheder. Shmel omsætter indsigten til brandkommunikation, indhold og digitale oplevelser. Sammen bevarer vi dansk identitet, historie og håndværk, mens vi tilpasser måden, fortællingen når kinesiske kunder og samarbejdspartnere på.',
  partnerOne: 'Indsigt i kinesisk marked og kultur<br>Strategi · Netværk · Muligheder',
  partnerTwo: 'Brand og kreativ formidling<br>Identitet · Indhold · Digitale oplevelser',
  aboutNote: 'Forslag til platformen: Virksomheder kan betale for at deltage, blive præsenteret eller gennemføre kampagner.',
  servicesEyebrow: 'BEVAR · TILPAS · SKAB',
  servicesTitle: 'Bevar din danske identitet.<br>Lad fortællingen nå længere.',
  servicesIntro: 'Dine produkter, din historie og dit håndværk er udgangspunktet. Vi lærer først dit brand at kende og beslutter derefter, hvad der skal bevares, tilpasses og skabes til et kinesisk publikum.',
  service1Title: 'Bevar det, der gør dig unik',
  service1Text: 'Vi gennemgår positionering, visuel identitet, tone og kernebudskaber. Dansk identitet, historie og håndværk forbliver kernen i dit brand.',
  service2Title: 'Tilpas måden, historien fortælles på',
  service2Text: 'Med research i det kinesiske marked tilpasser vi budskaber, visuel kommunikation, produktfortællinger og kunderejsen — fra informationshierarki og opfordringer til handling til indhold, der skaber tillid.',
  service3Title: 'Skab til dit nye publikum',
  service3Text: 'Vi skaber udvalgte websider, landingssider, produktpræsentationer og indhold til sociale medier målrettet Kina. De aftalte designs bliver til digitale oplevelser, der fungerer på tværs af enheder.',
  service1Tag: 'BEVAR / BRANDETS FUNDAMENT',
  service2Tag: 'TILPAS / KOMMUNIKATION',
  service3Tag: 'SKAB / INDHOLD OG DIGITALE OPLEVELSER',
  servicesExtra: 'Lad den samme fortælling gå igen på hjemmesider, i indhold, på emballage, menukort, skilte og tryksager.',
  servicesLink: 'Find din vej til et samarbejde',
  readinessEyebrow: 'KLAR TIL KINA / FRA INDSIGT TIL IMPLEMENTERING',
  readinessTitle: 'Forstå dit brand.<br>Skab det næste kapitel.',
  readinessIntro: 'Start med en betalt vurdering af dit brand og din hjemmeside samt research i det kinesiske marked. Vi aftaler, hvad der skal bevares, tilpasses og skabes, og vælger derefter den design- og udviklingsopgave, du har brug for. Omfanget aftaler vi sammen i hvert trin.',
  readinessCta: 'Start med en vurdering',
  step1Title: 'Forstå',
  step1Text: 'Vi gennemgår brandet og den eksisterende hjemmeside, finder huller i kommunikationen, undersøger kinesiske konkurrenter og hjemmesider i samme kategori og afdækker, hvilke oplysninger kunderne forventer.',
  step2Title: 'Tilpas',
  step2Text: 'Vi fastlægger struktur, informationshierarki, budskaber, opfordringer til handling, tillidsskabende indhold og produktpræsentation med den danske identitet som kerne.',
  step3Title: 'Design',
  step3Text: 'Vi redesigner de aftalte sider, tilpasser det visuelle udtryk, tilføjer indhold efter behov og udarbejder et koncept til en landingsside målrettet et kinesisk publikum.',
  step4Title: 'Implementér',
  step4Text: 'Vi udvikler de aftalte designs, tilpasser dem til forskellige skærmstørrelser, integrerer ændringerne og gennemgår oplevelsen før lancering.',
  guideTitle: 'Guide til brandtilpasning i Kina',
  guideText: 'En første leverance kan være en guide på 10–20 sider med positionering, kernebudskaber, visuel retning, kommunikationseksempler, anbefalinger til hjemmesiden og retning for sociale medier og indhold. Indhold og længde afhænger af det aftalte omfang.',
  workEyebrow: 'SHMELS KREATIVE PORTFOLIO',
  workTitle: 'Gode idéer.<br>Gjort synlige.',
  workIntro: 'Udvalgte projekter fra Shmel Agencys originale portfolio viser vores tilgang til brands, indhold og digitale oplevelser. Tilpasning til Kina kombinerer de kreative kompetencer med research, strategi og kunderejsen.',
  portfolioDownload: 'Se hele portfolioen (engelsk PDF)',
  filterAll: 'Alle projekter',
  filterBrand: 'Brand og emballage',
  filterDigital: 'Digitalt og sociale medier',
  filterCampaign: 'Kampagner og rum',
  portfolioNote: 'Eksemplerne viser kreative kompetencer og designarbejde. De dokumenterer ikke, at disse brands er kommet ind på det kinesiske marked gennem platformen.',
  showcaseFlow: 'Eksisterende hjemmeside → 3–5 konkrete observationer → Den kinesiske kunderejse → Koncept til redesign',
  showcaseText: 'I et eksempel på brandtilpasning tager vi udgangspunkt i den eksisterende hjemmeside og forklarer konkrete observationer om kommunikation og produktpræsentation. Derefter viser vi et koncept til en forside eller produktside med den kinesiske kunderejse som udgangspunkt. Designforslag markeres tydeligt som koncepter fra Shmel.',
  quote: '“Stærke produkter. En tydelig dansk identitet.<br>En fortælling tilpasset et kinesisk publikum.”',
  togetherText: 'Forestil dig et dansk møbelbrand. Gennemtænkt design, håndværk og historie er styrker, der skal bevares. Vi undersøger, hvordan hjemmesiden forklarer materialer, produktdetaljer og brandets fortælling, og hvordan kunderne opbygger tillid og tager næste skridt. Best of Denmark bidrager med markeds- og kulturindsigt. Shmel omsætter researchen til informationshierarki, produktfortællinger, visuel retning og et koncept til en forside eller produktside — fra at opdage brandet til at forstå det, få tillid og tage kontakt.',
  teamNote: 'Shmel blev grundlagt i 2026 og er et kreativt marketingbureau i opstartsfasen med et lille kerneteam og fleksible samarbejdspartnere til de enkelte projekter.',
  connectEyebrow: 'LAD OS SKABE DET NÆSTE KAPITEL',
  connectTitle: 'Den næste fortælling<br>starter med en samtale.',
  connectText: 'Er du et dansk brand, der udforsker Kina, eller en kinesisk samarbejdspartner med interesse for danske virksomheder? Start med dine mål og din eksisterende hjemmeside. Sammen finder vi det rigtige næste skridt.',
  connectCta: 'Opret et samarbejdsbrief',
  proposalDownload: 'Læs samarbejdsforslaget (engelsk PDF)',
  connectNote: 'Download dit brief og del det med teamet. Hjemmesiden indsender eller indsamler ikke dine oplysninger.',
  footer: 'Dansk inspiration. Muligheder i Kina.',
  backTop: 'Til toppen ↑',
  briefTitle: 'Dit samarbejdsbrief',
  briefIntro: 'Opret et brief, som du kan downloade og dele. Dine oplysninger bliver i din browser.',
  formName: 'Navn / virksomhed',
  formEmail: 'Kontaktmail (valgfri)',
  formInterest: 'Interesseområde',
  interest1: 'Brandsynlighed og erhvervssamarbejde',
  interest2: 'Brandvurdering og tilpasning til Kina',
  interest3: 'Webdesign, udvikling og indhold',
  formMessage: 'Dine mål, din eksisterende hjemmeside og det, du vil udforske',
  formDownload: 'Download dit brief ↓',
  briefSuccess: 'Dit brief er downloadet. Del det med din kontaktperson for samarbejdet.',
  waterEyebrow: 'TO KULTURER. ÉN FÆLLES STRØM.',
  waterTitle: 'Vi følger din rytme.<br>Og dykker lidt dybere.',
  waterIntro: 'Følg strømmen, når du scroller: En kinesisk vanddrage slynger sig gennem siden, mens en lille havfrue inspireret af København glider langs dens kurver. To kulturer, forbundet af vand.',
  waterAlt: 'En undervandsillustration af en kinesisk vanddrage, der møder en bronzefarvet lille havfrue på en sten.',
  dragonLabel: 'KINESISK VANDDRAGE',
  mermaidLabel: 'KØBENHAVN · DEN LILLE HAVFRUE',
  flowTitle: 'Vi følger din rytme',
  flowText: 'Dine mål. Dit tempo. Vi aftaler omfanget sammen og arbejder derefter med vurdering, strategi, design og udvikling i takt med dit brands behov.',
  diveTitle: 'Vi går i dybden med din virksomhed',
  diveText: 'Vi dykker ned i positionering, identitet, tone og kernebudskaber. Derefter gennemgår vi din eksisterende hjemmeside for at finde de steder, hvor fortællingen eller kunderejsen bliver uklar.',
  currentTitle: 'Vi følger de nye strømninger',
  currentText: 'Vi undersøger kinesiske konkurrenter, hjemmesider i samme kategori og publikums forventninger. Nye strømninger i kultur, visuel kommunikation og digitale oplevelser bliver til en retning, der stadig føles som dit brand.',
  languageLabel: 'Sprog',
  closeLabel: 'Luk',
  filtersLabel: 'Filtrér portfolio',
  navigationLabel: 'Hovednavigation',
  projectLabel: 'Se projekt: ',
  pageTitle: 'Best of Denmark × Shmel | Dansk inspiration. Muligheder i Kina.',
  briefFileHeading: 'Samarbejdsbrief',
  heroEyebrow: 'DANMARK MØDER KINA',
  flowEyebrow: '01 / DIN RYTME',
  diveEyebrow: '02 / I DYBDEN',
  currentEyebrow: '03 / NYE STRØMNINGER',
  brandHomeLabel: 'Best of Denmark — forsiden',
  heroScrollLabel: 'Scroll til introduktionen'
};

window.danishProjects = {
  dannis: {
    title: 'Danni’s Bar',
    tag: 'BRANDSTRATEGI · INDRETNING',
    description: 'Udviklet med idéen om et sted, hvor yngre og ældre generationer kan føle sig hjemme sammen. Shmel kombinerede markedsresearch, konkurrentanalyse, brandstrategi, visuel identitet, indretning, retning for sociale medier og marketingidéer. Vintageelementer og lokal nostalgi møder moderne design.'
  },
  luxury: {
    title: 'Luksusemballage',
    tag: 'EMBALLAGE · VISUEL RETNING',
    description: 'Eksempler på luksusemballage fra portfolioen, der udforsker visuel identitet, typografi og produktpræsentation.'
  },
  digital: {
    title: 'Digital brandoplevelse',
    tag: 'HJEMMESIDEKONCEPT · INTERFACEDESIGN',
    description: 'En visuel model af en hjemmeside fra portfolioen, der udforsker layout, visuelt hierarki og brandfortælling i en digital oplevelse. Eksemplet er et designkoncept.'
  },
  packaging: {
    title: 'Emballage med brandidentitet',
    tag: 'IDENTITET · PRODUKTEMBALLAGE',
    description: 'Udvalgt emballagedesign, der viser, hvordan en visuel identitet kan gå igen på produkter, etiketter og forskellige emballagetyper.'
  },
  events: {
    title: 'Events i byen',
    tag: 'EVENTMARKEDSFØRING · UDENDØRSREKLAME',
    description: 'Eksempler på eventreklame, hvor en fælles kreativ retning går igen i kampagnematerialer og visuelle modeller af udendørsreklamer.'
  },
  social: {
    title: 'Am.cor.inc på sociale medier',
    tag: 'SOCIALE MEDIER · INDHOLD',
    description: 'En Instagram-profil opbygget fra bunden med opslag, videoer, Stories, tekster og indhold samt analyse af profilens resultater og anbefalinger til sociale medier.'
  },
  caat: {
    title: 'CAAT! teateridentitet',
    tag: 'MASKOT · LOGODESIGN',
    description: 'En maskot og et logo til teaterstudiet CAAT!, hvor en udtryksfuld figur formidler brandets personlighed.'
  },
  posters: {
    title: 'Plakaternes visuelle sprog',
    tag: 'KREATIVT KONCEPT · PLAKATDESIGN',
    description: 'Plakateksempler, der kombinerer typografi, billeder og farver til et visuelt udtryk for events og kreative projekter.'
  },
  logos: {
    title: 'Små logoer. Stor personlighed.',
    tag: 'LOGODESIGN · VISUEL IDENTITET',
    description: 'Udvalgte logoeksperimenter fra portfolioen, der viser forskellige visuelle retninger og identitetsudtryk.'
  }
};
